import { Lead } from '@/types/lead';
import { calculateLeadScore } from './leadUtils';

export const sampleLeads: Lead[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah@techstartup.com',
    phone: '(555) 123-4567',
    company: 'TechStartup Inc',
    projectType: 'custom-development',
    budget: 'high',
    timeline: 'urgent',
    companySize: 'medium',
    status: 'new',
    score: 0,
    notes: 'Looking for a complete web application with user authentication and payment processing. Very interested in modern tech stack.',
    source: 'referral',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    name: 'Mike Chen',
    email: 'mike@localrestaurant.com',
    phone: '(555) 987-6543',
    company: 'Chen\'s Family Restaurant',
    projectType: 'website-redesign',
    budget: 'medium',
    timeline: 'soon',
    companySize: 'small',
    status: 'qualified',
    score: 0,
    notes: 'Current website is outdated. Needs online ordering system and mobile-friendly design.',
    source: 'cold-outreach',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    name: 'Jennifer Martinez',
    email: 'j.martinez@globalcorp.com',
    phone: '(555) 456-7890',
    company: 'Global Corp Solutions',
    projectType: 'ecommerce',
    budget: 'enterprise',
    timeline: 'soon',
    companySize: 'enterprise',
    status: 'contacted',
    score: 0,
    notes: 'Enterprise e-commerce platform with complex inventory management. Budget is flexible for the right solution.',
    source: 'website',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    name: 'David Wilson',
    email: 'david@smallbiz.net',
    phone: '(555) 321-0987',
    company: 'Wilson Consulting',
    projectType: 'maintenance',
    budget: 'low',
    timeline: 'future',
    companySize: 'small',
    status: 'proposal',
    score: 0,
    notes: 'Needs ongoing maintenance for existing WordPress site. Looking for reliable long-term partner.',
    source: 'social-media',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    name: 'Lisa Thompson',
    email: 'lisa@fashionboutique.com',
    phone: '(555) 654-3210',
    company: 'Thompson Fashion Boutique',
    projectType: 'ecommerce',
    budget: 'medium',
    timeline: 'urgent',
    companySize: 'small',
    status: 'won',
    score: 0,
    notes: 'Successfully closed! Building custom e-commerce site with inventory management and social media integration.',
    source: 'referral',
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '6',
    name: 'Robert Kim',
    email: 'robert@outdatedsite.com',
    phone: '',
    company: 'Kim Real Estate',
    projectType: 'website-redesign',
    budget: 'low',
    timeline: 'future',
    companySize: 'small',
    status: 'lost',
    score: 0,
    notes: 'Decided to go with a cheaper template solution. Not ready for custom development.',
    source: 'cold-outreach',
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  }
];

// Calculate scores for all sample leads
sampleLeads.forEach(lead => {
  lead.score = calculateLeadScore(lead);
});
